server:
  port: 9002
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848/
management:
  endpoint:
    web:
      exposure:
        include: '*'



